version: '3'
services:
  vprodb:
    image: app
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vproapp:
    image: app
    ports:
      - "8080:8080"
    volumes: 
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    image: web
    ports:
      - "80:80"
    deploy: 
     replicas: 1
     placement:
      constraints:
       - node.hostname == worker

volumes:
  vprodbdata: {}
  vproappdata: {}
